name: publish to nuget
on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      - name: Install dependencies
        run: dotnet restore

      # Build
      - name: Build solution and generate NuGet package
        run: |
          dotnet build --configuration Release --no-restore

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: IcanNet/IcanNet.csproj
          PACKAGE_NAME: IcanNet
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          TAG_FORMAT: '*'
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
